import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('console', m => { if (m.type() === 'error') console.log('[console.error]', m.text().slice(0,150)) })
page.on('response', r => {
  const u = r.url()
  if (u.includes('/api/') && r.status() >= 400) console.log('[http]', r.status(), u.replace(/^https?:\/\/[^/]+/, ''))
})
await page.goto('http://localhost:8081/login')
await page.getByPlaceholder(/用户名|username/i).fill('demo_admin')
await page.getByPlaceholder(/密码|password/i).fill('Demo@123456')
await page.getByRole('button', { name: /登\s*录|登录/ }).click()
await page.waitForURL(/workspace/, { timeout: 20000 })
await page.goto('http://localhost:8081/projects')
await page.getByRole('button', { name: 'Issue 列表' }).first().click()
await page.waitForTimeout(2500)
const noCell = await page.locator('tbody tr').first().locator('td').first().innerText()
console.log('编号单元格文本:', JSON.stringify(noCell))
await browser.close()
