import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://localhost:8081/login')
await page.getByPlaceholder(/用户名|username/i).fill('demo_admin')
await page.getByPlaceholder(/密码|password/i).fill('Demo@123456')
await page.getByRole('button', { name: /登\s*录|登录/ }).click()
await page.waitForURL(/workspace/, { timeout: 20000 })
await page.waitForTimeout(2000)
await page.screenshot({ path: 'D:/codex协同项目/wfx-fp0-workspace.png' })
// 项目空间：项目管理 → 看板（页签壳）
await page.goto('http://localhost:8081/projects')
await page.waitForTimeout(1500)
await page.getByRole('row', { name: /智慧校园/ }).getByRole('button', { name: '看板' }).click()
await page.waitForTimeout(1800)
await page.screenshot({ path: 'D:/codex协同项目/wfx-fp0-space.png' })
console.log('url:', page.url())
console.log('done')
await browser.close()
