import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://localhost:8081/login')
await page.getByPlaceholder(/用户名|username/i).fill('demo_admin')
await page.getByPlaceholder(/密码|password/i).fill('Demo@123456')
await page.getByRole('button', { name: /登\s*录|登录/ }).click()
await page.waitForURL(/workspace/, { timeout: 20000 })
// 抽屉：项目列表页第一行编号按钮
await page.goto('http://localhost:8081/projects')
await page.getByRole('button', { name: 'Issue 列表' }).first().click()
await page.waitForTimeout(2000)
const link = page.locator('tbody tr').first().locator('a, button').first()
console.log('first cell tag:', await link.evaluate(el => el.tagName))
await page.locator('tbody tr').first().getByRole('button').first().click()
await page.waitForTimeout(1800)
await page.screenshot({ path: 'D:/codex协同项目/wfx-fp1-drawer.png' })
console.log('done')
await browser.close()
